#!/bin/bash
echo "=== Testing AI Companion Integration ==="
echo ""
echo "Opening browser to test page..."
echo "URL: http://localhost:3000/topics/changing-states"
echo ""
echo "What to test:"
echo "  1. ✓ Page loads with particle simulation"
echo "  2. ✓ Companion avatar visible (bottom-right)"
echo "  3. ✓ No 'AI companion offline' warning"
echo "  4. ✓ Heat/cool buttons work"
echo "  5. ✓ Companion reacts to simulation events"
echo "  6. ✓ Click companion to open chat"
echo "  7. ✓ Ask: 'What happens when ice melts?'"
echo ""
echo "Backend logs: tail -f agent/.venv/lib/python3.12/site-packages/uvicorn/*.log"
echo "Frontend logs: Check browser console (F12)"
echo ""
read -p "Press Enter to open browser..." 
open http://localhost:3000/topics/changing-states 2>/dev/null || \
xdg-open http://localhost:3000/topics/changing-states 2>/dev/null || \
echo "Please open http://localhost:3000/topics/changing-states manually"
